/*
SQLyog Ultimate v13.1.1 (64 bit)
MySQL - 10.4.32-MariaDB : Database - ai_chatbot_bos
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`ai_chatbot_bos` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;

USE `ai_chatbot_bos`;

/*Table structure for table `tx_qa_log` */

DROP TABLE IF EXISTS `tx_qa_log`;

CREATE TABLE `tx_qa_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `question` longtext DEFAULT NULL,
  `answer` longtext DEFAULT NULL,
  `upvote` int(11) DEFAULT NULL,
  `downvote` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

/*Data for the table `tx_qa_log` */

insert  into `tx_qa_log`(`id`,`question`,`answer`,`upvote`,`downvote`,`created_at`) values 
(12,'Jelaskan komponen pembinaan dan pengembangan prestasi?','(4) Bagi sekolah yang memiliki prestasi yang ditetapkan sebagai sekolah pengimbas, selain komponen penggunaan Dana BOS Kinerja sebagaimana dimaksud pada ayat (3), juga harus melaksanakan komponen pembinaan dan pengembangan prestasi.\n-8-  (3) Komponen penggunaan Dana BOS Kinerja bagi sekolah yang memiliki prestasi sebagaimana dimaksud pada ayat (1) huruf b meliputi: a. asesmen dan pemetaan talenta; b. pelatihan dan pengembangan talenta; dan/atau c. pengembangan manajemen dan ekosistem.\nd. Pembinaan dan pengembangan prestasi satuan pendidikan melalui program pengimbasan untuk sekolah pengimbas merupakan komponen yang digunakan untuk pembiayaan kegiatan pembinaan dan pengembangan kepada satuan pendidikan yang belum berprestasi, seperti: 1) pengembangan kapasitas sumber daya manusia talenta sekolah imbas; 2) kegiatan pemberian pendampingan dan layanan konsultasi pelaksanaan pengembangan program manajemen talenta bagi sekolah imbas; 3) pengembangan talenta sekolah imbas melalui kemitraan; 4) penyelenggaraan kompetisi lokal antar sekolah bersama sekolah imbas; dan/atau 5) kegiatan lain yang relevan dalam rangka pembinaan dan pengembangan prestasi sekolah imbas.',1,1,'2025-03-24 08:57:20'),
(13,'Bagaimana cara menghitung besaran Dana BOSP?','Terjadi kesalahan saat mengambil jawaban.',0,0,'2025-03-24 15:21:23'),
(14,'Kemana saya bisa mendapatkan informasi lebih lanjut tentang Dana BOSP?','(2) Penyampaian laporan realisasi penggunaan Dana BOSP sebagaimana dimaksud pada ayat (1) dilaksanakan paling lambat: a. tanggal 31 Juli tahun anggaran berkenaan untuk laporan realisasi pengunaan Dana BOP PAUD Reguler, Dana BOS Reguler, atau Dana BOP Kesetaraan Reguler tahap I yang ada di Satuan Pendidikan; dan b. tanggal 31 Januari tahun anggaran berikutnya untuk laporan realisasi keseluruhan penggunaan Dana BOSP yang diterima dalam satu tahun anggaran.\nDana Bantuan Operasional Sekolah yang selanjutnya disebut Dana BOS adalah Dana BOSP untuk operasional Satuan Pendidikan dalam menyelenggarakan pendidikan dasar dan pendidikan menengah.\nDana Bantuan Operasional Satuan Pendidikan yang selanjutnya disebut Dana BOSP adalah dana alokasi khusus nonfisik untuk mendukung biaya operasional nonpersonalia bagi Satuan Pendidikan.',0,0,'2025-03-24 15:22:46'),
(15,'Apa perbedaan antara Dana BOS Reguler dan Dana BOS Kinerja?','(2) Dana BOS sebagaimana dimaksud pada ayat (1) terdiri atas: a. Dana BOS Reguler; dan b. Dana BOS Kinerja.\nDana Bantuan Operasional Sekolah Reguler yang selanjutnya disebut Dana BOS Reguler adalah Dana BOS yang digunakan untuk membiayai kegiatan operasional rutin Satuan Pendidikan dalam menyelenggarakan pendidikan dasar dan menengah.\n-6-  (3) Dana BOP PAUD sebagaimana dimaksud pada ayat (1) terdiri atas: a. Dana BOP PAUD Reguler; dan b. Dana BOP PAUD Kinerja.',0,0,'2025-03-24 15:23:28'),
(16,'Apakah sekolah swasta juga berhak menerima Dana BOS?','(2a) Komponen penggunaan Dana BOS Kinerja bagi sekolah yang melaksanakan Program Sekolah Penggerak sebagaimana dimaksud pada ayat (1) huruf a yang ditetapkan sebagai pelaksana program pengimbasan yaitu pembinaan dan pengembangan Satuan Pendidikan lain untuk melakukan peningkatan mutu.\nDana Bantuan Operasional Sekolah yang selanjutnya disebut Dana BOS adalah Dana BOSP untuk operasional Satuan Pendidikan dalam menyelenggarakan pendidikan dasar dan pendidikan menengah.\nKomponen Penggunaan Dana BOS Kinerja untuk Sekolah yang Melaksanakan Program Sekolah Penggerak yang ditetapkan sebagai pelaksana Program pengimbasan adalah pembinaan dan pengembangan transformasi kepada satuan pendidikan lain untuk melakukan peningkatan mutu dalam hal pengembangan sumber daya manusia, pembelajaran kurikulum merdeka, digitalisasi sekolah, dan perencanaan berbasis data yang dilaksanakan dalam bentuk kegiatan seperti: a. pelatihan; b. penguatan komunitas belajar; dan c. pendampingan.',0,0,'2025-03-24 15:24:18'),
(17,'Apa yang dimaksud dengan RKAS dalam pengelolaan Dana BOSP?','(2) Dana BOS sebagaimana dimaksud pada ayat (1) terdiri atas: a. Dana BOS Reguler; dan b. Dana BOS Kinerja.\n(2) Pemantauan dan evaluasi sebagaimana dimaksud pada ayat (1) dilakukan terhadap: a. program kebijakan; dan b. pengelolaan Dana BOSP.\n(2) Penyampaian laporan realisasi penggunaan Dana BOSP sebagaimana dimaksud pada ayat (1) dilaksanakan paling lambat: a. tanggal 31 Juli tahun anggaran berkenaan untuk laporan realisasi pengunaan Dana BOP PAUD Reguler, Dana BOS Reguler, atau Dana BOP Kesetaraan Reguler tahap I yang ada di Satuan Pendidikan; dan b. tanggal 31 Januari tahun anggaran berikutnya untuk laporan realisasi keseluruhan penggunaan Dana BOSP yang diterima dalam satu tahun anggaran.',0,0,'2025-03-24 15:24:59'),
(18,'Apa dasar hukum perubahan kebijakan Dana BOS dalam Permendikbudristek No. 63 Tahun 2023?','(2) Pemantauan dan evaluasi sebagaimana dimaksud pada ayat (1) dilakukan terhadap: a. program kebijakan; dan b. pengelolaan Dana BOSP.\n(2) Penyampaian laporan realisasi penggunaan Dana BOSP sebagaimana dimaksud pada ayat (1) dilaksanakan paling lambat: a. tanggal 31 Juli tahun anggaran berkenaan untuk laporan realisasi pengunaan Dana BOP PAUD Reguler, Dana BOS Reguler, atau Dana BOP Kesetaraan Reguler tahap I yang ada di Satuan Pendidikan; dan b. tanggal 31 Januari tahun anggaran berikutnya untuk laporan realisasi keseluruhan penggunaan Dana BOSP yang diterima dalam satu tahun anggaran.\nKetentuan ayat (2) Pasal 51 diubah, dan Ketentuan Pasal 51 ayat (3) dan ayat (4) dihapus, sehingga Pasal 51 berbunyi sebagai berikut: Pasal 51 (1) Kepala Satuan Pendidikan penerima Dana BOSP harus menyampaikan laporan realisasi penggunaan Dana BOSP melalui sistem aplikasi yang disediakan oleh Kementerian.',0,0,'2025-03-24 15:27:17'),
(19,'Apa saja komponen penggunaan Dana BOS menurut aturan terbaru?','(2) Dana BOS sebagaimana dimaksud pada ayat (1) terdiri atas: a. Dana BOS Reguler; dan b. Dana BOS Kinerja.\n(2) Penyampaian laporan realisasi penggunaan Dana BOSP sebagaimana dimaksud pada ayat (1) dilaksanakan paling lambat: a. tanggal 31 Juli tahun anggaran berkenaan untuk laporan realisasi pengunaan Dana BOP PAUD Reguler, Dana BOS Reguler, atau Dana BOP Kesetaraan Reguler tahap I yang ada di Satuan Pendidikan; dan b. tanggal 31 Januari tahun anggaran berikutnya untuk laporan realisasi keseluruhan penggunaan Dana BOSP yang diterima dalam satu tahun anggaran.\nKetentuan ayat (2) Pasal 51 diubah, dan Ketentuan Pasal 51 ayat (3) dan ayat (4) dihapus, sehingga Pasal 51 berbunyi sebagai berikut: Pasal 51 (1) Kepala Satuan Pendidikan penerima Dana BOSP harus menyampaikan laporan realisasi penggunaan Dana BOSP melalui sistem aplikasi yang disediakan oleh Kementerian.',0,0,'2025-03-24 15:27:54'),
(20,'Bagaimana cara sekolah menggunakan Dana BOS untuk asesmen dan pemetaan talenta?','Rincian Komponen Penggunaan Dana BOS Kinerja Sekolah yang Memiliki Prestasi a. Asesmen dan Pemetaan Talenta merupakan komponen yang digunakan untuk pembiayaan kegiatan pelaksanaan asesmen dan pemetaan talenta peserta didik, seperti: 1) penyelenggaraan asesmen talenta peserta didik; 2) evaluasi dan inovasi sistem asesmen talenta peserta didik; dan/atau 3) kegiatan lainnya yang relevan dalam rangka pelaksanaan asesmen dan pemetaan talenta.\n-8-  (3) Komponen penggunaan Dana BOS Kinerja bagi sekolah yang memiliki prestasi sebagaimana dimaksud pada ayat (1) huruf b meliputi: a. asesmen dan pemetaan talenta; b. pelatihan dan pengembangan talenta; dan/atau c. pengembangan manajemen dan ekosistem.\nKomponen Penggunaan Dana BOS Kinerja untuk Sekolah yang Melaksanakan Program Sekolah Penggerak yang ditetapkan sebagai pelaksana Program pengimbasan adalah pembinaan dan pengembangan transformasi kepada satuan pendidikan lain untuk melakukan peningkatan mutu dalam hal pengembangan sumber daya manusia, pembelajaran kurikulum merdeka, digitalisasi sekolah, dan perencanaan berbasis data yang dilaksanakan dalam bentuk kegiatan seperti: a. pelatihan; b. penguatan komunitas belajar; dan c. pendampingan.',0,0,'2025-03-24 15:39:10'),
(21,'Siapa saja yang berhak menerima Dana BOS berdasarkan regulasi ini?','(2) Dana BOS sebagaimana dimaksud pada ayat (1) terdiri atas: a. Dana BOS Reguler; dan b. Dana BOS Kinerja.\n(2) Penyampaian laporan realisasi penggunaan Dana BOSP sebagaimana dimaksud pada ayat (1) dilaksanakan paling lambat: a. tanggal 31 Juli tahun anggaran berkenaan untuk laporan realisasi pengunaan Dana BOP PAUD Reguler, Dana BOS Reguler, atau Dana BOP Kesetaraan Reguler tahap I yang ada di Satuan Pendidikan; dan b. tanggal 31 Januari tahun anggaran berikutnya untuk laporan realisasi keseluruhan penggunaan Dana BOSP yang diterima dalam satu tahun anggaran.\n(2) Laporan realisasi keseluruhan sebagaimana dimaksud dalam Pasal 52 dan laporan realisasi minimal 50% (lima puluh persen) penggunaan Dana BOP PAUD Reguler, Dana BOS Reguler, atau Dana BOP Kesetaraan Reguler yang diterima pada tahap I menjadi dasar penyaluran tahap II tahun anggaran berkenaan.',0,0,'2025-03-24 15:41:08'),
(22,'Apa yang dimaksud dengan Dana BOP PAUD?','Dana Bantuan Operasional Penyelenggaraan Pendidikan Anak Usia Dini Reguler yang selanjutnya disebut Dana BOP PAUD Reguler adalah Dana BOP PAUD yang digunakan untuk membiayai kegiatan operasional rutin Satuan Pendidikan dalam menyelenggarakan layanan pendidikan anak usia dini.\n-6-  (3) Dana BOP PAUD sebagaimana dimaksud pada ayat (1) terdiri atas: a. Dana BOP PAUD Reguler; dan b. Dana BOP PAUD Kinerja.\nDana Bantuan Operasional Penyelenggaraan Pendidikan Anak Usia Dini yang selanjutnya disebut Dana BOP PAUD adalah Dana B  Satuan Pendidikan dalam menyelenggarakan layanan pendidikan anak usia dini.',0,0,'2025-03-24 15:43:40'),
(23,'Apa yang dimaksud dengan Satuan Pendidikan?','Dinas Pendidikan yang selanjutnya disebut Dinas adalah perangkat daerah yang merupakan unsur pembantu kepala daerah dalam penyelenggaraan urusan pemerintahan di bidang pendidikan.\n(2) Satuan Pendidikan sebagaimana dimaksud pada ayat (1) meliputi: a. taman kanak-kanak; b. kelompok bermain; c. taman penitipan anak; d. Satuan PAUD sejenis; e. sanggar kegiatan belajar; dan f. pusat kegiatan belajar masyarakat.\nSekolah Luar Biasa yang selanjutnya disingkat SLB adalah bentuk Satuan Pendidikan khusus yang terintegrasi pada jalur formal untuk satuan pendidikan anak usia dini dan jenjang pendidikan dasar sampai dengan pendidikan menengah dalam satu manajemen pengelolaan.',0,0,'2025-03-24 15:44:27'),
(24,'Satuan Pendidikan apa saja yang menerima Dana BOS?','Dana Bantuan Operasional Sekolah yang selanjutnya disebut Dana BOS adalah Dana BOSP untuk operasional Satuan Pendidikan dalam menyelenggarakan pendidikan dasar dan pendidikan menengah.\nDana Bantuan Operasional Sekolah Kinerja yang selanjutnya disebut Dana BOS Kinerja adalah Dana BOS yang digunakan untuk peningkatan mutu pendidikan Satuan Pendidikan yang menyelenggarakan pendidikan dasar dan pendidikan menengah yang dinilai berkinerja baik.\n(2a) Komponen penggunaan Dana BOS Kinerja bagi sekolah yang melaksanakan Program Sekolah Penggerak sebagaimana dimaksud pada ayat (1) huruf a yang ditetapkan sebagai pelaksana program pengimbasan yaitu pembinaan dan pengembangan Satuan Pendidikan lain untuk melakukan peningkatan mutu.',0,0,'2025-03-24 15:44:51'),
(25,'Apakah SLB termasuk penerima Dana BOS?','(2) Dana BOS sebagaimana dimaksud pada ayat (1) terdiri atas: a. Dana BOS Reguler; dan b. Dana BOS Kinerja.\nDana Bantuan Operasional Sekolah yang selanjutnya disebut Dana BOS adalah Dana BOSP untuk operasional Satuan Pendidikan dalam menyelenggarakan pendidikan dasar dan pendidikan menengah.\nDana Bantuan Operasional Satuan Pendidikan yang selanjutnya disebut Dana BOSP adalah dana alokasi khusus nonfisik untuk mendukung biaya operasional nonpersonalia bagi Satuan Pendidikan.',0,0,'2025-03-24 15:45:17'),
(26,'Apakah SLB termasuk satuan pendidikan penerima Dana BOS?','(2a) Komponen penggunaan Dana BOS Kinerja bagi sekolah yang melaksanakan Program Sekolah Penggerak sebagaimana dimaksud pada ayat (1) huruf a yang ditetapkan sebagai pelaksana program pengimbasan yaitu pembinaan dan pengembangan Satuan Pendidikan lain untuk melakukan peningkatan mutu.\nDana Bantuan Operasional Sekolah yang selanjutnya disebut Dana BOS adalah Dana BOSP untuk operasional Satuan Pendidikan dalam menyelenggarakan pendidikan dasar dan pendidikan menengah.\nDana Bantuan Operasional Sekolah Kinerja yang selanjutnya disebut Dana BOS Kinerja adalah Dana BOS yang digunakan untuk peningkatan mutu pendidikan Satuan Pendidikan yang menyelenggarakan pendidikan dasar dan pendidikan menengah yang dinilai berkinerja baik.',0,0,'2025-03-24 15:46:49'),
(27,'Untuk apa saja Dana BOS Kinerja dapat digunakan?','(2) Dana BOS sebagaimana dimaksud pada ayat (1) terdiri atas: a. Dana BOS Reguler; dan b. Dana BOS Kinerja.\nDana Bantuan Operasional Sekolah Kinerja yang selanjutnya disebut Dana BOS Kinerja adalah Dana BOS yang digunakan untuk peningkatan mutu pendidikan Satuan Pendidikan yang menyelenggarakan pendidikan dasar dan pendidikan menengah yang dinilai berkinerja baik.\nDana Bantuan Operasional Satuan Pendidikan yang selanjutnya disebut Dana BOSP adalah dana alokasi khusus nonfisik untuk mendukung biaya operasional nonpersonalia bagi Satuan Pendidikan.',0,0,'2025-03-24 15:47:34'),
(28,'Komponen penggunaan Dana BOP PAUD Kinerja meliputi apa saja?','-6-  (3) Dana BOP PAUD sebagaimana dimaksud pada ayat (1) terdiri atas: a. Dana BOP PAUD Reguler; dan b. Dana BOP PAUD Kinerja.\n(2) Laporan realisasi keseluruhan sebagaimana dimaksud dalam Pasal 52 dan laporan realisasi minimal 50% (lima puluh persen) penggunaan Dana BOP PAUD Reguler, Dana BOS Reguler, atau Dana BOP Kesetaraan Reguler yang diterima pada tahap I menjadi dasar penyaluran tahap II tahun anggaran berkenaan.\n(2) Dana BOS sebagaimana dimaksud pada ayat (1) terdiri atas: a. Dana BOS Reguler; dan b. Dana BOS Kinerja.',0,0,'2025-03-24 15:47:54');

/*Table structure for table `tx_suggestion` */

DROP TABLE IF EXISTS `tx_suggestion`;

CREATE TABLE `tx_suggestion` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `question` text DEFAULT NULL,
  `category` text DEFAULT NULL,
  `description` text DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

/*Data for the table `tx_suggestion` */

insert  into `tx_suggestion`(`id`,`question`,`category`,`description`,`created_at`) values 
(1,'Apa yang dimaksud dengan Dana BOSP?','Definisi','Pasal 1 (definition of Dana BOSP)','2025-03-24 22:04:13'),
(2,'Apa yang dimaksud dengan Dana BOP PAUD?','Definisi','Pasal 1 (definition of Dana BOP PAUD)','2025-03-24 22:04:13'),
(3,'Apa yang dimaksud dengan Dana BOS Reguler?','Definisi','Pasal 1 (definition of Dana BOS Reguler)','2025-03-24 22:04:13'),
(4,'Apa yang dimaksud dengan Dana BOP Kesetaraan?','Definisi','Pasal 1 (definition of BOP Kesetaraan)','2025-03-24 22:04:13'),
(5,'Apa perbedaan antara Dana BOS Reguler dan Dana BOS Kinerja?','Definisi','Pasal 1, Pasal 7 (definitions and types of BOS funds)','2025-03-24 22:04:13'),
(6,'Apa yang dimaksud dengan Satuan Pendidikan?','Definisi','Pasal 1','2025-03-24 22:04:13'),
(7,'Satuan Pendidikan apa saja yang menerima Dana BOS?','Kelayakan','Pasal 7 (lists eligible schools: SD, SMP, SMA, SLB, SMK)','2025-03-24 22:04:13'),
(8,'Siapa yang menerima Dana BOP PAUD?','Kelayakan','Pasal 4','2025-03-24 22:04:13'),
(9,'Apakah SLB termasuk penerima Dana BOS?','Kelayakan','Pasal 7','2025-03-24 22:04:13'),
(10,'Untuk apa saja Dana BOS Kinerja dapat digunakan?','Penggunaan Dana','Pasal 42 (detailed breakdown of uses, including for Program Sekolah Penggerak, schools with achievements, and schools with the best progress)','2025-03-24 22:04:13'),
(11,'Komponen penggunaan Dana BOP PAUD Kinerja meliputi apa saja?','Penggunaan Dana','Pasal 37 (lists components: human resource development, independent curriculum learning, school digitization, data-based planning)','2025-03-24 22:04:13'),
(12,'Bagaimana Dana BOS Kinerja digunakan untuk sekolah yang melaksanakan Program Sekolah Penggerak?','Penggunaan Dana','Pasal 42 (specifically addresses the use for Program Sekolah Penggerak)','2025-03-24 22:04:13'),
(13,'Apa saja komponen penggunaan Dana BOS Reguler?','Penggunaan Dana','There is no specific pasal, because it is for general operational.','2025-03-24 22:04:13'),
(14,'Apakah Dana BOSP dapat digunakan untuk pengembangan sumber daya manusia?','Penggunaan Dana','Pasal 37, Pasal 42 (this is a key component for Kinerja funds)','2025-03-24 22:04:13'),
(15,'Apa itu pembelajaran kurikulum merdeka dalam penggunaan Dana BOSP?','Penggunaan Dana','Pasal 37, Pasal 42','2025-03-24 22:04:13'),
(16,'Kapan laporan realisasi penggunaan Dana BOSP harus disampaikan?','Pelaporan & Administrasi','Pasal 51 (specifies deadlines: July 31 for the first stage, January 31 for the full year)','2025-03-24 22:04:13'),
(17,'Bagaimana cara menyampaikan laporan realisasi penggunaan Dana BOSP?','Pelaporan & Administrasi','Pasal 51 (states that reports are submitted through the application system provided by the Ministry)','2025-03-24 22:04:13'),
(18,'Apa yang dimaksud dengan RKAS dalam pengelolaan Dana BOSP?','Pelaporan & Administrasi','Pasal 1 angka 24','2025-03-24 22:04:13'),
(19,'Apa yang dimaksud dengan Program Sekolah Penggerak?','Program Sekolah Penggerak','Pasal 1 (definition) and recurring throughout the document in the context of Dana BOS Kinerja.','2025-03-24 22:04:13'),
(20,'Bagaimana sekolah pengimbas menggunakan Dana BOS Kinerja?','Program Sekolah Penggerak','Pasal 42','2025-03-24 22:04:13');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
